name = "kantv"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# 默认 D1 数据库配置（用于命令行操作）
[[d1_databases]]
binding = "DB"
database_name = "tv"
database_id = "6e9651fa-c446-432a-a6d9-c593e8ff8b8f"
